### ISSUE TITLE
Remove node-modules folder

### ISSUE THREAD

**Issue by RangerMauve** [quantumfoam/DVNA#15]
Keeping the node_modules folder in git [isn't advised](https://docs.npmjs.com/misc/faq#should-i-check-my-node-modules-folder-into-git). It'd be better to set up your package.json file properly and maybe use [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) if you really care about ensuring specific modules get installed.

**Comment by quantumfoam** [comment]
General good advice, thanks!
