### ISSUE TITLE
Why separate applications?

### ISSUE THREAD

**Issue by ash47** [quantumfoam/DVNA#22]
Why is each vulnerability in a separate application? You should build a global module that each of the vulnerabilities use to register themselves, then, if you insist on making them each be their own server, have a little website that starts and stops the server for each vulnerability, it would probably be better if each had their own page, instead of own server though.

**Comment by quantumfoam** [comment]
Originally for testing the vulnerabilities but agreed there should be an exported module with all the vulnerabilities working. Submit PR?

**Comment by ash47** [comment]
PR?

**Comment by fcsonline** [comment]
I'm working on a PR to rule them all registering each vulnerability in a shared server. I will publish it as soon as possible.

**Comment by quantumfoam** [comment]
You rock @fcsonline - no rush though. Commit at your pace :+1:

**Comment by fcsonline** [comment]
Done! :muscle: https://github.com/quantumfoam/DVNA/pull/23

**Comment by quantumfoam** [comment]
Fixed in https://github.com/quantumfoam/DVNA/pull/23
