### ISSUE TITLE
command_injection Vulnerability Does Not use Tainted Input

### ISSUE THREAD

**Issue by matt-** [quantumfoam/DVNA#29]
Unless I am missing something in this vulnerability, no user input is passed to child_process.exec.

https://github.com/quantumfoam/DVNA/blob/master/vulnerabilities/command_injection/vulnerability.js#L8
I expected something like: 

exe.exec('id ' + req.query.e , function(err, data) {

**Comment by quantumfoam** [comment]
Thanks for pointing this out @matt- I'll keep the issue open until the vulnerabilities are updated.
