### ISSUE TITLE
Setup?

### ISSUE THREAD

**Issue by misterch0c** [quantumfoam/DVNA#6]
Hi,
I've tried to run DVNA but I can't make it work.

This is what I did:

1. clone the repo
2. npm install (fails because no package.json)
3. node dvna.js
4. access https://127.0.0.1:6666

And I get this error:

```
This webpage is not available

ERR_UNSAFE_PORT
```
Did I miss something?

**Comment by caseydunham** [comment]
I'm new to NodeJS, but I'm having trouble on Ubuntu 14.04 as well. npm install fails because there is no package.json file that describes the dependencies.

**Comment by quantumfoam** [comment]
@misterch0c @caseydunham Thanks for your interest in the project, however, it's currently not ready for use yet. I'll make sure to update the project page so that it reflects it's still a work in progress.

**Comment by quantumfoam** [comment]
@misterch0c @caseydunham Check the updated project setup page. There's no UI for the application right now so each issue (JS file) is its own challenge. I'm working on getting a page setup for challenge navigation.

**Comment by misterch0c** [comment]
That's what I thought, but should at least see a white page if I run node vuln.js & then browse to my localhost on port 6666 right? I always get page not available

**Comment by quantumfoam** [comment]
@misterch0c Send me an email (see profile). Maybe a Slack instance instead? Checking into that cross-browser issue.
