### ISSUE TITLE
Include more challenges

### ISSUE THREAD

**Issue by quantumfoam** [quantumfoam/DVNA#9]
See some of the reported security advisories and build challenges around older node versions.

**Comment by fcsonline** [comment]
It could be interesting, before add more new stuff, to define the guidelines to create a new vulnerability example. I had some interesting ideas like:

- Add some documentation for each one challenging the player to achieve something.
- Add some kind of mark to know that a player has complete a vulnerability.

I can create a skeleton for the documentation, if you are ok with that.

**Comment by quantumfoam** [comment]
Yes, track it under issue #2
